Carousel
Touchstack/BargainMoto-New pull request #54
Opened 2023-11-28 18:55 UTC by Ewabunmi

![bargain6](https://github.com/Touchstack/BargainMoto-New/assets/123972532/be729e8c-ab82-41b7-b242-51bd9f982567)
![bargain7](https://github.com/Touchs
![bargain13](https://github.com/Touchstack/BargainMoto-New/assets/123972532/519d873b-9efc-4ae4-a93e-b0c3e45ee7be)
tack/B
![bargain12](https://github.com/Touchstack/BargainMoto-New/assets/123972532/2be71d30-dd0e-4e92-9917-6af77109672f)
argainMoto-New/assets/123972532/1db3e051-3ff
![bargain5](https://github.com/Touchst
![bargain10](https://github.com/Touchstack/BargainMoto-New/assets/123972532/d9132d7a-a3c8-4e6e-9655-baf5733666fc)
ack/BargainMoto-New/assets/123972532/eca2abe5-a322-475b-8fc2-5e31b80b8094)
1-4d6e-8171-10760d6f2ff2)
![bargain8](https://github.com/Touchstack/BargainMoto-New/assets/123972532/d9bef
![bargain4](https://github.com/Touchstack/BargainMoto-New/assets/123972532/fb3af6e5-fd26-4e49-bf0b-79335340676d)
24b-5311-4d94-b
![bargain1](https://github.com/Touchstack/BargainMoto-New/assets/123972532/788cbf9a-7b7d-43dd-a4ad-62d5e5650c80)
ecd-5988959e1113)
![bargain9](https://github.com/Touchstack/BargainMoto-New/assets/123972532/40125489-1431-4ea7-a908-00dbfaa09124)

2023-11-28 23:30 UTC, krepinnegga commented
Looks Good to me

2023-11-29 09:10 UTC, EugeneSantaclausian requested changes
@Ewabunmi  please comment out the seller's review component for now. We do not have that implemented on the backend yet.

2023-11-29 09:12 UTC, Ewabunmi commented
Noted.

On Wed, Nov 29, 2023 at 10:11 AM Eugene Dumoga ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @Ewabunmi <https://github.com/Ewabunmi> please comment out the seller's
> review component for now. We do not have that implemented on the backend
> yet.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Touchstack/BargainMoto-New/pull/54#pullrequestreview-1754774657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5R2XNDWZAY265GKAQPJXP3YG332LAVCNFSM6AAAAAA76HSRUWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONJUG43TINRVG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-05 18:59 UTC, krepinnegga approved these changes

2023-12-07 11:07 UTC, merged